name: test_job_Ali
on:
  workflow_dispatch:
env:
#   # This item has no matching transformer
#   org.jenkinsci.plugins.builduser.BuildUser:
#     plugin: build-user-vars-plugin@1.5
jobs:
  build:
    runs-on:
      - self-hosted
      - qdw_secondary
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: run batch command
      shell: cmd
      run: |-
        IF NOT EXIST "E:\Ali_test\testing_permissions\test.ps1" exit -1
        PowerShell.exe -ExecutionPolicy ByPass -noprofile -file "E:\Ali_test\testing_permissions\test.ps1"
